In [2]:
import numpy as np #alias -> np

In [ ]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [ ]:
# dimensions and shape of an array
arr.ndim

1

In [6]:
arr =np.array(34)
arr.ndim

1

In [7]:
a = np.array([[[[]]]])
a.ndim
a.shape

(1, 1, 1, 0)

In [8]:
range = np.arange(1,10, 2) #start, stop, step

In [9]:
range

array([1, 3, 5, 7, 9])

In [10]:
arr = np.linspace(0,1,10) #start, stop, number of values
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [12]:
arr = np.logspace(1, 3, 2) #logarithmic scale array -> 10^1 -> 10^3 ... 3 points
arr

array([  10., 1000.])

In [ ]:
# np.logspace(start, ending -> powers, 3 -> number of values)

In [ ]:
# np.zeros -> array full of zeros
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [ ]:
arr = np.zeros([2,3]) #array full of zeros
arr


array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr = np.ones([4,2]) #array full of ones.
arr

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
arr = np.full(10, 2) #-> create an array full of any value
arr

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
arr = np.full([2,4], 7.1) #[row, column], default value
arr

array([[7.1, 7.1, 7.1, 7.1],
       [7.1, 7.1, 7.1, 7.1]])

In [ ]:
arr = np.empty([2,3]) #Uninitialized array -> create an array without setting any values
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr = np.random.rand(10)
arr #-> random floats(0 to 1)

array([0.62348907, 0.31973819, 0.96809577, 0.13022212, 0.46859814,
       0.88857456, 0.2449654 , 0.53686729, 0.7200564 , 0.41848488])

In [ ]:
arr = np.random.rand(2,3)
arr

array([[0.44835859, 0.63997847, 0.38655507],
       [0.00720327, 0.45839394, 0.50871393]])

In [ ]:
arr = np.random.randn(2,3)
arr #-> random floats from standard normal distribution

array([[1.65576131, 0.11674059, 0.54939477],
       [1.40401884, 0.16041226, 0.63944705]])

In [19]:
arr = np.random.randint(10, 100) #->start, stop, dimension/number of values
arr#-> random integers

52

In [22]:
arr = np.random.randint(10, 100, size = (2,3)) #->start, stop, dimension/number of values
arr

array([[55, 46, 23],
       [38, 90, 83]])

## Numpy Data Types and Type Casting

In [ ]:
arr = np.array([1,2,3.1,4,5])
arr

array([1. , 2. , 3.1, 4. , 5. ])

In [ ]:
arr.dtype

dtype('float64')

In [ ]:
lst = ["string", 1, 2, 5.6]
arr = np.array(lst)
arr

array(['string', '1', '2', '5.6'], dtype='<U32')

In [ ]:
arr = np.array(["1",2,3.1,4,5])
arr

array(['1', '2', '3.1', '4', '5'], dtype='<U32')

In [ ]:
arr.dtype

dtype('<U32')

In [24]:
arr = np.array([1.1, 2.6 , 3 , 4], dtype = np.int64)

In [25]:
arr.dtype

dtype('int64')

In [26]:
arr

array([1, 2, 3, 4])

In [ ]:
#type casting -> astype()

In [ ]:
arr = np.array([1,2,3])
arr.dtype

dtype('int64')

In [ ]:
new_arr = arr.astype(np.float64)
new_arr

array([1., 2., 3.])

In [ ]:
new_arr.dtype

dtype('float64')

In [ ]:
new_arr2 = new_arr.astype(np.int64)
new_arr2

array([1, 2, 3])

In [23]:
# Type Casting errors:
import pandas as pd
arr = np.array(["1", "2", "hello"])
# Use pd.to_numeric to handle non-numeric values, coercing them to NaN
arr_numeric = pd.to_numeric(arr, errors='coerce')
# Fill NaN values with 0 (or another appropriate value) and then convert to int
arr2 = arr_numeric.fillna(0).astype(np.int64)
arr2

ValueError: invalid literal for int() with base 10: np.str_('hello')

In [ ]:
arr = np.array([[1,2,3],
                [4,5,6]])

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr.ndim

2

In [ ]:
arr.shape

(2, 3)

In [ ]:
arr.size

6

In [ ]:
arr.itemsize

8

Array Reshaping -> Reshape, Ravel, flatten

In [ ]:
# Reshape
arr = np.array([1,2,3,4,5,6])
reshaped = arr.reshape(2,3)
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [ ]:
reshape2 = reshaped.reshape(3,2)

In [ ]:
reshape2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
#ravel -> convert 1D array
ravel = reshape2.ravel()
ravel

array([100,   2,   3,   4,   5,   6])

In [ ]:
ravel[0] = 100
print(ravel)
print(reshape2)

[100   2   3   4   5   6]
[[100   2]
 [  3   4]
 [  5   6]]


In [ ]:
#flatten -> to 1D array
# -> returns a copy of the array

flat = reshape2.flatten()
flat

array([100,   2,   3,   4,   5,   6])

In [ ]:
flat[0] = 1

In [ ]:
flat

array([1, 2, 3, 4, 5, 6])

In [ ]:
reshape2

array([[100,   2],
       [  3,   4],
       [  5,   6]])

# Arithmetic Operations on Arrays

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])


In [ ]:
#addition:

print(a+b)

[5 7 9]


In [ ]:
# subtraction
print(b-a)

[3 3 3]


In [ ]:
#division:
print(a/b)

[0.25 0.4  0.5 ]


In [ ]:
# integer division
print(b//a)

[4 2 2]


In [ ]:
#multiplication
print(a*b)

[ 4 10 18]


In [ ]:
#modulus -> remainder
print(b%a)

[0 1 0]


In [ ]:
# exponent -> power
print(a**2)

[1 4 9]


Universal Function -> ufuncs

In [ ]:
arr = np.array([1,4,9,16])

In [ ]:
# Square root -> np.sqrt()

print(np.sqrt(arr))

[1. 2. 3. 4.]


In [ ]:
# exponentioal -> np.exp -> e^x -> x is any integer

print(np.exp([1,2]))

[2.71828183 7.3890561 ]


In [ ]:
#sine function -> np.sin

angles = np.array([0, np.pi/2, np.pi])
print(np.sin(angles))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]


Indexing and Slicing


In [29]:
a = [1,2,3,4,5]

In [ ]:
a[-1:-4: -1]

[5, 4, 3]

In [ ]:
a[: :2]

[1, 3, 5]

In [ ]:
arr = np.array([10,20,30,40,50])
# indexes = 0, 2, 4
arr[::2]

array([10, 30, 50])

In [ ]:
# Negative Indexing
print(arr[-1])

50


In [ ]:
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

In [ ]:
print(matrix[0:2, :])

[[1 2 3]
 [4 5 6]]


In [ ]:
print(matrix[1: , 1:])

[[5 6]
 [8 9]]


In [ ]:
#np.take -> built in function to perform indexing and slicing
arr = np.array([10,20,30,40,50])
ind = [0, 2]
print(np.take(arr, ind))

[10 30]


In [ ]:
# Iterating with nditer()

In [ ]:
arr= np.array([[1,2], [3,4]])

In [ ]:
for x in np.nditer(arr):
  print(x, end = " ")

1 2 3 4 

In [ ]:
# ndenumerate() -> both index + value

for ind, x in np.ndenumerate(arr):
  print(ind, x)



(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


In [ ]:
# Views vs Copies

arr = np.array([1,2,3,4,5])
view = arr[1:3]
view

array([2, 3])

In [ ]:
view[0] = 200

In [ ]:
view

array([200,   3])

In [ ]:
arr

array([  1, 200,   3,   4,   5])

In [ ]:
# copy
copy = arr[1:3].copy()
copy

array([200,   3])

In [ ]:
copy[0] = 2
copy

array([2, 3])

In [ ]:
arr

array([  1, 200,   3,   4,   5])

In [ ]:
arr = np.array([[1,2], [3,4]])
arr

array([[1, 2],
       [3, 4]])

In [ ]:
print(arr.transpose())

[[1 3]
 [2 4]]


In [ ]:
# Swapaxes -> swap 2 specific axes in a matrix.

arr = np.array([[[1,2], [3,4]]])
arr.shape

(1, 2, 2)

In [ ]:
swap = np.swapaxes(arr, 0, 1)
swap.shape

(2, 1, 2)

In [ ]:
# Concatenation:

a = np.array([1,2])
b = np.array([3,4])

In [ ]:
combine = np.concatenate((a,b))
combine

array([1, 2, 3, 4])

In [ ]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])

In [ ]:
print(np.vstack((arr1, arr2)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
print(np.hstack((arr1, arr2)))

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
print(np.stack((arr1, arr2), axis = 0))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
print(np.stack((arr1, arr2), axis = 1))

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [ ]:
# Splitting Arrays:

arr1 = np.array([[1,2], [3,4], [5,6], [7,8]])

In [ ]:
arr1

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
print(np.split(arr1, 4))

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]]), array([[7, 8]])]


In [ ]:
print(np.hsplit(arr1, 2))

[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]])]


In [ ]:
#Repeating:

arr = np.array([1,2,3])
print(np.repeat(arr,3))

[1 1 1 2 2 2 3 3 3]


In [ ]:
# tile -> repeat my whole array

print(np.tile(arr, 2))

[1 2 3 1 2 3]


In [ ]:
#Aggregate Functions:

arr = np.array([1,2,3])
print(np.sum(arr))

6


In [ ]:
np.mean(arr)

np.float64(2.0)

In [ ]:
np.median(arr)

np.float64(2.0)

In [ ]:
np.std(arr)

np.float64(0.816496580927726)

In [ ]:
np.var(arr)

np.float64(0.6666666666666666)

In [ ]:
np.max(arr)

np.int64(3)

In [ ]:
np.min(arr)

np.int64(1)

In [ ]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print(np.sum(matrix, axis = 0))

[12 15 18]


In [ ]:
# Cumulative Operations -> running total

arr

array([1, 2, 3])

In [ ]:
print(np.cumsum(arr))

[1 3 6]


In [ ]:
print(np.cumprod(arr))

[1 2 6]


Conditional Based choices


In [ ]:
# Where:

arr

array([1, 2, 3])

In [ ]:
result = np.where(arr <2, "low", "high")

In [ ]:
result

array(['low', 'high', 'high'], dtype='<U4')

In [ ]:
arr

array([1, 2, 3])

In [ ]:
#argwhere: row-column positions for 2d arrays

In [ ]:
arr

array([1, 2, 3])

In [ ]:
print(np.argwhere(arr>0))

[[0]
 [1]
 [2]]


In [ ]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print(np.argwhere(matrix> 5))

[[1 2]
 [2 0]
 [2 1]
 [2 2]]


In [ ]:
# Logical and:

arr

array([1, 2, 3])

In [ ]:
mask = np.logical_and(arr > 3, arr < 6)

In [ ]:
arr[mask]

array([], dtype=int64)

In [ ]:
# logical or:

mask = np.logical_or(arr < 4, arr > 5)
mask

array([ True,  True,  True])

In [ ]:
arr[mask]

array([1, 2, 3])

In [ ]:
arr2 = np.array([0, 1, 5, 0, 5])
arr2

array([0, 1, 5, 0, 5])

In [ ]:
print(np.nonzero(arr2))

(array([1, 2, 4]),)


In [ ]:
# Broadcasting

In [ ]:
image = np.array([[200, 150], [100, 250]])
image.shape

(2, 2)

In [ ]:
brightness = image + 50
brightness

array([[250, 200],
       [150, 300]])

In [ ]:
# Vectorization:

# np.vectorize() -> convert a regular function to be applied on an array.

In [ ]:
def square(x):
  return x*x

vfunc = np.vectorize(square)

In [ ]:
arr

array([1, 2, 3])

In [ ]:
print(vfunc(arr))

[1 4 9]


In [ ]:
# Dealing With Missing values:

# np.nan -> not a number.

In [ ]:
a = np.array([1, 2, np.nan, 4])

In [ ]:
a

array([ 1.,  2., nan,  4.])

In [ ]:
# np.inf and -np.inf -> positive and negative infinites

In [ ]:
# np.isnan
# np.isinf
# np.isfinite

# --> these are the functions used to detect any null values, infinte value or fnite value

In [ ]:
print(np.isnan(a))

[False False  True False]


In [ ]:
b = np.array([1, np.nan, np.inf, 10.2, 40])

In [ ]:
print(np.isinf(b))

[False False  True False False]


In [ ]:
new_b = np.nan_to_num(b) # remove Nan/ infinite values.

In [ ]:
new_b

array([1.00000000e+000, 0.00000000e+000, 1.79769313e+308, 1.02000000e+001,
       4.00000000e+001])